name: Test with external id and failure
on:
  workflow_dispatch

jobs:
  runJob:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3.1.0

      - name: "Extract branch name"
        id: get_ref
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> "$GITHUB_OUTPUT"

      - name: "Trigger workflow"
        id: dispatch
        uses: ./
        with:
          workflow-name: extId_dummy_with_fail.yml
          use-marker-step: true
          token: ${{ secrets.WF_TRIGGER_TOKEN }}
          ref: ${{ steps.get_ref.outputs.branch }}

      - name: "Wait to complete"
        id: wait
        uses: ./
        with:
          token: ${{ secrets.WF_TRIGGER_TOKEN }}
          run-id: ${{ steps.dispatch.outputs.run-id }}

      - name: Check result
        run: |
          if [[ "completed" != "${{ steps.wait.outputs.run-status }}" ]] ||
            [[ "failure" != "${{ steps.wait.outputs.run-conclusion }}" ]] ||
            [[ false -ne ${{ steps.wait.outputs.failed }} ]]; then
            echo "Run-Status should be <completed> but was <${{ steps.wait.outputs.run-status }}>"
            echo "Run-Conclusion should be <failure> but was <${{ steps.wait.outputs.run-conclusion }}>"
            echo "Failed should be <false> but was <${{ steps.wait.outputs.failed }}>"
            exit 1
          else
            echo "Checks passed"
          fi
